dependencies:
  - python=3.12
  - anaconda::pango>=1.42.0
  - anaconda::pandas>=1.3.2
  - conda-forge::psycopg2
  - conda-forge::open-fonts
  - conda-forge::xorg-libxrender
  - conda-forge::xorg-libxext
  - conda-forge::xorg-libxau
